import { Inter, Lato } from "next/font/google";
import "./globals.css";

import { NextUIProvider } from "@nextui-org/react";


const inter = Lato({ subsets: ["latin"], weight: ['100', '300', '400', '700',] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: "auto" }}>

        <div className="mx-auto  ">

          {/* <AuthProvider> */}
            <NextUIProvider >
              {children}
            </NextUIProvider>
          {/* </AuthProvider> */}
        </div>
      </body>
    </html>
  );
}
